mongo:
  image: mongo
  container_name: mongo
  restart: always
  ports: 
    - "27017:27017"
  volumes_from: 
    -  mongodata
 
mongodata:
  image: mongo
  container_name: mongodata
  volumes:
   - /home/hushuming/dbdata/mongodb:/data/db
  command: --break-mongo

    
useraccount:
  image: user-account:0.0.1-SNAPSHOT
  container_name: useraccount
  hostname: useraccount
  restart: always
  links:  
    - mongo
  ports:
    - "8001:8001"

    

  
