version: '2'
services:

  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      -  mongo-data:/data/db:rw
    networks:
      - wfij


  useraccount:
    image: user-account:0.0.1-SNAPSHOT
    container_name: useraccount
    hostname: useraccount
    restart: always
    environment:
      DOMAIN_NAME: 192.168.1.110
    ports:
      - "8001:8001"
    networks:
      - wfij



networks:
  wfij:
    external:
      name: wfij-net

volumes:
  mongo-data:
    external: true




