version: '2'
services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes_from:
      -  mongodata
    networks:
      - wfij

  mongodata:
    image: mongo
    volumes:
   # 产品发布时，需要更改地址
       - /home/keryhu/dbdata/mongodb:/data/db
    command: --break-mongo



  useraccount:
    image: user-account:0.0.1-SNAPSHOT
    container_name: useraccount
    restart: always
    ports:
      - "8001:8001"
    networks:
      - wfij


networks:
  wfij:
    driver: bridge




