version: '2'
services:

  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes_from:
      -  mongodata
    networks:
      - wfij

  mongodata:
    image: mongo
    volumes:
      - /home/keryhu/dbdata/mongodb:/data/db
    command: --break-mongo


  useraccount:
    image: user-account:0.0.1-SNAPSHOT
    container_name: useraccount
    restart: always
# 通过环境变量，让useraccount访问mongo
    environment:
      MONGO_HOST: mongo
    ports:
      - "8001:8001"
    networks:
      - wfij
    depends_on:
      - mongo



networks:
  wfij:
    external:
      name: wfij-net





